/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import { BsFillMoonStarsFill } from "react-icons/bs";
import { useState } from "react";
import Image from "next/image";
import Falls from "../public/falls.jpg";
import Trails from "../public/trails.gif";
import Lake from "../public/lake.jpg";
import AiBear from "../public/bear.png";
import Lottie from "lottie-react";
import TwitterAni from "../public/twitter.json";
import CameraAnimation from "../public/camera.json";
import InstaAni from "../public/insta.json";
import ThreadAni from "../public/thread.json";
import BlockAni from "../public/blockchain.json";
import { useRef } from "react";
import { Wallet } from "../public/wallet.tsx";

export default function Home() {
  const [darkMode, setDarkMode] = useState(true);
  return (
    <div className={darkMode ? "dark" : ""}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className=" bg-white px-10 dark:bg-gray-900 md:px-20 lg:px-40">
        <section className="min-h-screen">
          <nav className="pt-10 mb-1 flex justify-between dark:text-white">
          
          <div className="shadow-lg rounded-xl  dark:bg-stone-200 pr-2">
          <ul className="flex items-center">
          <a  href="https://twitter.com/KnowlesPhotos"><Lottie className=""
            animationData={TwitterAni}
            style={{height: 65}} /></a>
            <a  href="https://Threads.net/@knowles.sol"><Lottie className=""
            animationData={ThreadAni}
            style={{height: 80}} /></a>
            <a  href="https://www.instagram.com/knowles.sol/"><Lottie className=""
            animationData={InstaAni}
            style={{height: 50}} /></a>
            
            </ul>
            </div>
          
            <ul className="flex items-center">
              <li>
                <BsFillMoonStarsFill
                  onClick={() => setDarkMode(!darkMode)}
                  className=" cursor-pointer text-2xl"
                />
              </li>
              <li>
                <a
                  className="bg-gradient-to-r from-cyan-500 text- to-red-500 text-white px-4 py-2 border-none rounded-md ml-8"
                  href="#"
                >
                  Exchange.art
                </a>
              </li>
              <li>
              <a  href="https://exchange.art/knowles"><Lottie className=""
            animationData={CameraAnimation}
            style={{height: 80}} /></a>
              </li>
            </ul>
          </nav>
          <div className="text-center p-10 py-10">
            <h2 className="text-5xl py-2 text-red-600 font-medium dark:text-red-400 md:text-6xl">
              Cameron Knowles
            </h2>
            <h3 className="text-2xl py-2 dark:text-white md:text-3xl">
              Photography, AI and Solana Web3
            </h3>
            <p className="text-md py-5 leading-8 text-gray-800 dark:text-gray-200 max-w-xl mx-auto md:text-xl">
              Landscape photography from my wonderful adventures 
              living in B.C. Canada. AI Art and Web3 Sol Tools
            </p>
            <div className="text-5xl flex justify-center gap-20 py-10 text-stone-100 dark:text-stone-100">
            
            </div>
            <section>
          <div className="lg:flex gap-10">
            
            <div className="text-center shadow-lg p-10 rounded-xl my-10  dark:bg-stone-200 flex-1">
              <Image className="rounded-bl-3xl rounded-tr-3xl" src={Falls} width={350} height={250} />
              <h3 className="text-lg font-medium pt-8 pb-2  ">
                Photography
              </h3>
              <p className="py-2">
                Creating elegant designs suited for your needs following core
                design theory.
              </p>
              
              <h4 className="py-4 text-red-600">Main Camera Gear I Use</h4>
              <p className="text-gray-800 py-1">Sony a7R</p>
              <p className="text-gray-800 py-1">Canon 7D</p>
              <p className="text-gray-800 py-1">Figma</p>
              <p className="text-gray-800 py-1">Indesign</p>
            </div>
            
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-stone-200 flex-1">
              <Image className="rounded-bl-3xl rounded-tr-3xl" src={Trails} width={250} height={250} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">
                Generative Code Art
              </h3>
              <p className="py-2">
                Do you have an idea for your next great website? Lets make it a
                reality.
              </p>
              <h4 className="py-4 text-red-600">Coding Tools/Libraries I Use</h4>
              <p className="text-gray-800 py-1">P5.js</p>
              <p className="text-gray-800 py-1">Microsoft VSC</p>
              <p className="text-gray-800 py-1">Adobe Cloud</p>
            
            </div>
            <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-stone-200 flex-1">
              <Image className="rounded-bl-3xl rounded-tr-3xl" src={AiBear} width={400} height={250} />
              <h3 className="text-lg font-medium pt-8 pb-2 ">AI</h3>
              <p className="py-2">
                A series of AI generated art with a irl shot photography image
                used as a base model. From dark spooky to beautiful landsacpes, I
                love creating with AI.
              </p>
              <h4 className="py-4 text-red-600">AI Tools I Use</h4>
              <p className="text-gray-800 py-1">MidJourney</p>
              <p className="text-gray-800 py-1">StableDiffusion models</p>
              <p className="text-gray-800 py-1">Photoshop</p>
              <p className="text-gray-800 py-1">Lightroom</p>
            </div>
          </div>
        </section>
          </div>
        </section>
        <section>
        <div className="text-center shadow-lg p-10 rounded-xl my-10 dark:bg-stone-200 flex-1">
        <h3 className="text-3xl py-2 text-red-600 font-medium dark:text-red-500 md:text-6xl">
              Solana Blockchain Connect
            </h3>
        <Wallet></Wallet>
        <Lottie className=""
            animationData={BlockAni}
            style={{height: 100}} />
            </div>
        </section>
        <div className="rounded-3xl rounded-tr-3xl py-10 w-800 h-80 relative overflow-hidden">
              <Image src={Lake} layout="fill" objectFit="cover" />
            </div>
      </main>
    </div>
  );
}
